print("=====================")
print("   SELEÇÃO DE TIMES  ")
print("=====================\n")

print("1. São Paulo")
print("2. Flamengo")
print("3. Ponte Preta")
print("4. Santos")
print("5. Palmeiras")
preferido = input("Escolha uma das opções acima: ")